const Erros = {
  DESCONHECIDO: 'DESCONHECIDO',
  EMAIL_INVALIDO: 'EMAIL_INVALIDO',
  ID_INVALIDO: 'ID_INVALIDO',
  NOME_PEQUENO: 'NOME_PEQUENO',
  NOME_VAZIO: 'NOME_VAZIO',
  NOME_GRANDE: 'NOME_GRANDE',
  NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
  NOME_CARACTERES_ESPECIAIS: 'NOME_CARACTERES_ESPECIAIS',
} as const

export default Erros
