const Erros = {
  AULA_DURACAO_ZERADA: 'AULA_DURACAO_ZERADA',
  CAPITULO_SEM_AULAS: 'CAPITULO_SEM_AULAS',
  DESCONHECIDO: 'DESCONHECIDO',
  DURACAO_INVALIDA: 'DURACAO_INVALIDA',
  DURACAO_ZERADA: 'DURACAO_ZERADA',
  EMAIL_INVALIDO: 'EMAIL_INVALIDO',
  ID_INVALIDO: 'ID_INVALIDO',
  NOME_CARACTERES_ESPECIAIS: 'NOME_CARACTERES_ESPECIAIS',
  NOME_GRANDE: 'NOME_GRANDE',
  NOME_PEQUENO: 'NOME_PEQUENO',
  NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
  NOME_VAZIO: 'NOME_VAZIO',
  ORDEM_INVALIDA: 'ORDEM_INVALIDA',
  SENHA_FRACA: 'SENHA_FRACA',
  SENHA_HASH_INVALIDA: 'SENHA_HASH_INVALIDA',
  URL_INVALIDA: 'URL_INVALIDA',
  CURSO_SEM_DURACAO: 'CURSO_SEM_DURACAO',
  CURSO_SEM_AULAS: 'CURSO_SEM_AULAS',
} as const

export default Erros
