const Erros = {
  NOME_CARACTERES_INVALIDOS: 'NOME_CARACTERES_INVALIDOS',
  NOME_GRANDE: 'NOME_GRANDE',
  NOME_PEQUENO: 'NOME_PEQUENO',
  NOME_SEM_SOBREBOME: 'NOME_SEM_SOBREBOME',
  NOME_VAZIO: 'NOME_VAZIO',
  SENHA_INVALIDA: 'SENHA_INVALIDA',
} as const

export default Erros
